name: Devops project real 5

on:
  push:
    branches: ["main"]

jobs:
  devops-real5-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setpu python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Formatting test
      run: black .
    
    - name: Lint test
      run: flake8 . || echo "Linting done"
    
    - name: Static analysis
      run: bandit -r .

    - name: Unit test
      run: pytest test_app.py  

      #Creds rectified      

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: docker build -t shepherd777/devops-real-5:latest .

    - name: Push
      run: docker push shepherd777/devops-real-5:latest
